name: thutohub
description: A simple lessons app MVP for Hackathon.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  supabase_flutter: ^2.0.0  # For Supabase integration
  google_generative_ai: ^0.4.7    #For AI Backbone
  flutter_tts: ^3.8.5
  
=======
  supabase_flutter: ^2.12.0
  google_generative_ai: ^0.4.7
  flutter_tts: ^3.8.5
  flutter_dotenv: ^6.0.0   # Good â€” this is the latest stable as of early 2026
>>>>>>> d0a41dcf8f6b0487a27d12e9528400beec2b0d67

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
<<<<<<< HEAD
  uses-material-design: true
=======
  uses-material-design: true
  assets:
    -  assets/config.env
>>>>>>> d0a41dcf8f6b0487a27d12e9528400beec2b0d67
